### ISSUE TITLE
Carousel not working even in your example

### ISSUE THREAD

**Issue by masroorejaz** [jmagrippis/svelte-carousel#2]
Hello,

I have tried your Carousel and it's not working properly on desktop (working fine on mobile). Even in your given [example url ](https://svelte-carousel-alpha.vercel.app/) it's not working properly on desktop. 

Kindly please fix it. 

Thank you.

**Comment by jmagrippis** [comment]
Hey @masroorejaz , thanks for checking this out!

Could you let me know exactly what you mean with "not working properly"? I assumed you meant that, when you click on the nav items, the relevant picture does not go to the middle of the screen on bigger screens?

I made the change for this, let me know if it works for you. The PR looks big as I migrated to the latest dependencies in general, but I think it was mostly adding the `{ inline: 'center' }` option for `scrollIntoView`:

https://github.com/jmagrippis/svelte-carousel/pull/3/commits/833aaa666d1d07d271f4383fa2554b997ac77bec#diff-e50f6e9198ab8eb14d0d6a00bb131e26769a584ebfd46b8930a9384fd5ad773cR13

So maybe I did fix what you meant, but maybe not, let me know 🙂
